### ISSUE TITLE
Error in "semantic-release" when triggering a GitHub release

### ISSUE THREAD

**Issue by iainjreid** [emphori/actions#1]
Triggered from https://github.com/Emphori/drowsy/runs/709898590

```
RequestError [HttpError]: Cookies must be enabled to use GitHub.
    at /home/runner/work/_actions/Emphori/actions/master/semantic-release/lib/index.js:2:521929
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'HttpError',
  status: 403,
  headers: {
    'cache-control': 'no-cache',
```

**Comment by iainjreid** [comment]
This appears to be resolved upstream, [here](https://github.com/semantic-release/semantic-release/issues/1557). A rebuild of the "sematic-release" action should resolve the issue.

**Comment by iainjreid** [comment]
Fixed!
